version: "3"
services:
  rpc:
    image: mrpompy/bas-template-bsc:devel
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/testnet.json"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@34.81.119.47:30303"
      - "--networkid=17243"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,trace,txpool"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.api=eth,net,web3,debug,trace,txpool"
      - "--ws.port=8546"
      - "--ws.origins=*"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "/datadir/testnet.json:/datadir/testnet.json"
      - "/datadir/keystore:/datadir/keystore"
      - "/datadir/password.txt:/datadir/password.txt"
      - "/datadir/rpc:/datadir/geth"
    restart: always
    
  blockscout-db:
    depends_on:
      - rpc
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./datadir/blockscout:/var/lib/postgresql/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "7432:5432"
  blockscout:
    depends_on:
      - blockscout-db
    image: blockscout/blockscout:${DOCKER_TAG:-4.1.5}
    restart: always
    links:
      - blockscout-db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      ETHEREUM_JSONRPC_VARIANT: "geth"
      BLOCK_TRANSFORMER: "clique"
      ETHEREUM_JSONRPC_HTTP_URL: "http://host.docker.internal:8545/"
      DATABASE_URL: "postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false"
      ECTO_USE_SSL: "false"
    ports:
      - "4000:4000"