version: 2.1

jobs:
 build-branch:
   machine: true
   steps:
     - checkout
     - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: docker build -f Dockerfile.alltools -t ankrnetwork/bas-template-bsc:$CIRCLE_BRANCH .
     - run: docker push ankrnetwork/bas-template-bsc:$CIRCLE_BRANCH
 build-latest:
   machine: true
   steps:
     - checkout
     - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: docker build -f Dockerfile.alltools -t ankrnetwork/bas-template-bsc:latest .
     - run: docker push ankrnetwork/bas-template-bsc:latest

workflows:
  build-deploy:
    jobs:
      - build-branch:
          context:
            - docker_deploy
          filters:
            branches:
              only: [ devel ]
      - build-latest:
          context:
            - docker_deploy
          filters:
            branches:
              only: [ master ]